### ISSUE TITLE
BadZipFile error in 04_word2vec_visualize.py

### ISSUE THREAD

**Issue by angoodkind** [chiphuyen/stanford-tensorflow-tutorials#48]
When trying to run this code, I get the error below. The zip file looks okay to me, though.
```

(tensorflow) adamg:examples adamg$ python 04_word2vec_visualize.py
Dataset ready
Traceback (most recent call last):
  File "04_word2vec_visualize.py", line 157, in <module>
    main()
  File "04_word2vec_visualize.py", line 153, in main
    batch_gen = process_data(VOCAB_SIZE, BATCH_SIZE, SKIP_WINDOW)
  File "/Users/adamg/Dropbox/Programming Tutorials/MachineLearning/TensorFlow/Stanford-tf-repo/examples/process_data.py", line 90, in process_data
    words = read_data(file_path)
  File "/Users/adamg/Dropbox/Programming Tutorials/MachineLearning/TensorFlow/Stanford-tf-repo/examples/process_data.py", line 43, in read_data
    with zipfile.ZipFile(file_path) as f:
  File "/Users/adamg/anaconda/envs/tensorflow/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/Users/adamg/anaconda/envs/tensorflow/lib/python3.5/zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by HighWay-To-Hell** [comment]
hi,  I just encounter this problem too :( .  Did you solve this problem? If you do, and still remember how you solved it,  Can you tell me how to solve this. I am new to programming. Would be very appreciate if you can give me some guide. If you don't remember this issue, still would be appreciate for you time : )
